CREATE TABLE IF NOT EXISTS app_state (
  username VARCHAR(100) PRIMARY KEY,
  revision INT NOT NULL DEFAULT 0,
  payload MEDIUMTEXT NOT NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS login_limits (
  bucket CHAR(64) PRIMARY KEY,
  failures INT NOT NULL DEFAULT 0,
  window_start BIGINT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
